# Generated by Django 4.2.15 on 2024-08-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0002_remove_asset_id_asset_asset_id_asset_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.BigIntegerField(editable=False),
        ),
    ]
